---
.release_template: &release_definition
  image: docker:latest
  stage: release
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker info
    - echo "Registry Address ${CONTAINER_REGISTRY_ADDRESS}"
    - echo "Registry Password ${CONTAINER_REGISTRY_PASSWORD}"
    - echo "Registry username ${CONTAINER_REGISTRY_USERNAME}"
    - docker login -u ${CONTAINER_REGISTRY_USERNAME} -p ${CONTAINER_REGISTRY_PASSWORD} ${CONTAINER_REGISTRY_ADDRESS}
    - docker load --input ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}.tar
    - docker tag ${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  script:
    - docker push ${CONTAINER_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  needs: ["build"]
  only:
    refs:
      - /^([0-9]+)\.([0-9]+)\.([0-9]+)(-.+)?/i


release_to_okd4_teh1_registry:
  <<: *release_definition
  variables:
    OKD4_TEH1_REGISTRY: "image-registry.apps.private.okd4.teh-1.snappcloud.io"
    CONTAINER_REGISTRY_ADDRESS: "$OKD4_TEH1_REGISTRY"
    CONTAINER_REGISTRY_IMAGE: "$OKD4_TEH1_REGISTRY/snappcloud-unified-panel/$CI_PROJECT_NAME"
    CONTAINER_REGISTRY_USERNAME: "gitlab-ci"
    CONTAINER_REGISTRY_PASSWORD: ${OKD4_TEH1_SNAPPCLOUD_OBJSTORE_TOKEN}

release_to_okd4_teh2_registry:
  <<: *release_definition
  variables:
    OKD4_TEH2_REGISTRY: "image-registry.apps.private.okd4.teh-2.snappcloud.io"
    CONTAINER_REGISTRY_ADDRESS: "$OKD4_TEH2_REGISTRY"
    CONTAINER_REGISTRY_IMAGE: "$OKD4_TEH2_REGISTRY/snappcloud-unified-panel/$CI_PROJECT_NAME"
    CONTAINER_REGISTRY_USERNAME: "gitlab-ci"
    CONTAINER_REGISTRY_PASSWORD: ${OKD4_TEH2_SNAPPCLOUD_OBJSTORE_TOKEN}
