apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: spcld-objectstorage-panel-backend
  name: object-store-registry-editor
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-editor
subjects:
  - kind: ServiceAccount
    name: object-store-gitlab-ci
    namespace: {{ .Release.Namespace }}