---
stages:
  - build
  - release
#  - test
#  - static_scanning
#  - container_scanning

include:
  - local: .gitlab/ci/templates/build.gitlab-ci.yml
  - local: .gitlab/ci/templates/release.gitlab-ci.yml
#  - local: .gitlab/ci/templates/test.gitlab-ci.yml
#  - local: .gitlab/ci/templates/radar-static-scanning.gitlab-ci.yml
#  - local: .gitlab/ci/templates/radar-container-scanning.gitlab-ci.yml
