apiVersion: v2
name: s3-panel
description: A Helm chart for S3 Panel
type: application
version: 1.0.0
dependencies:
- name: snapp-object-storage-subchart
  version: 1.0.0
  repository: file://charts/snapp-object-storage-subchart
  alias: snapp-object-store
- name: snapp-object-storage-subchart
  version: 1.0.0
  repository: file://charts/snapp-object-storage-subchart
  alias: snapp-object-store-dev