{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snappobjectstore.name" . }}-app-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    logger:
      level: {{ .Values.config.log_level }}
    server:
      address: {{ .Values.config.address | quote }}
      port: {{ .Values.config.port }}
      auth_enabled: {{ .Values.config.auth_enabled | quote }}
      auth_key_lookup: "header:Authorization"
      auth_token: {{ .Values.auth_token | quote }}
      download_path: {{ .Values.config.download_path | quote }}
    object_storage_config:
      url: {{ .Values.config.url | quote }}
      access_key: {{ .Values.access_key }}
      secret_key: {{ .Values.secret_key }}
{{- end }}