snapp-object-store:
  enabled: false
  fqdn: ""
  config:
    url: ""
    address: "0.0.0.0"
    port: 8080
    log_level: "warn"
    auth_enabled: "false"
    auth_token: ""
snapp-object-store-dev:
  enabled: false
  fqdn: ""
  config:
    url: ""
    address: "0.0.0.0"
    port: 8080
    log_level: "debug"
    auth_enabled: "false"
    auth_token: ""