// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://swagger.io/terms/",
        "contact": {
            "name": "Cloud-Platform",
            "url": "https://docs.snappcloud.io/docs/servicedesk",
            "email": "cloud-platform@snappcloud.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/bucket/create": {
            "post": {
                "description": "Creates bucket for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bucket"
                ],
                "summary": "Creates Bucket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Bucket Name to Create",
                        "name": "bucket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Bucket created successfully",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.BucketCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Bucket Already Exists / Bucket creation quota exceeded",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/bucket/delete": {
            "delete": {
                "description": "Deletes bucket for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bucket"
                ],
                "summary": "Deletes Bucket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Bucket Name to Delete",
                        "name": "bucket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Bucket deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.BucketDeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/bucket/list": {
            "get": {
                "description": "Fetches list of buckets owned by a user that is specified by AccessKey and SecretKey",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bucket"
                ],
                "summary": "List of buckets of a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "search by given string, could be empty",
                        "name": "search_string",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "max keys in a page",
                        "name": "max_keys",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with bucket list",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.BucketListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/bucket/quota": {
            "get": {
                "description": "Fetches Quota of buckets owned by a user that is specified by AccessKey. if status code is 200 and the BucketQuotaResponse hard_bytes or hard_objects is -1, mean no limitation on quota_storage or quota_objects is applied.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bucket"
                ],
                "summary": "Quota of buckets of a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "search by given string, could be empty",
                        "name": "search_string",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "max keys in a page",
                        "name": "max_keys",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with buckets quota",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.BucketQuotaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/object/delete": {
            "delete": {
                "description": "Deletes a list of objects specified by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Object"
                ],
                "summary": "Deletes the list of objects inside a bucket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "objects names",
                        "name": "objects",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with objects delete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectDeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Object Does not exist",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/object/download": {
            "get": {
                "description": "This functions downloads an object from bucket.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Object"
                ],
                "summary": "download an object to bucket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "object name",
                        "name": "object",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with bucket download",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectDownloadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/object/head": {
            "get": {
                "description": "check if an object exists",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Object"
                ],
                "summary": "check if an object exists",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "objects name",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with objects head",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectHeadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/object/list": {
            "get": {
                "description": "Fetches list of buckets owned by a user that is specified by AccessKey and SecretKey",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Object"
                ],
                "summary": "List of objects of a bucket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "max_keys of pagination",
                        "name": "max_keys",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "page of pagination",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "search by given string, could be empty",
                        "name": "search_string",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with bucket list",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/object/share": {
            "get": {
                "description": "This function uses the PreSign feature of S3 to share object link with expiration time with users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Object"
                ],
                "summary": "share the preSign address of object",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "objects name",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "default": "1h",
                        "description": "URL expiration time",
                        "name": "expiration",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with object url",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectShareResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/object/upload": {
            "post": {
                "description": "This functions uploads an object to bucket.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Object"
                ],
                "summary": "upload an object to bucket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User given SecretKey",
                        "name": "secret_key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "bucket name",
                        "name": "bucket",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with bucket upload",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "409": {
                        "description": "Already Exists",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/user/id": {
            "get": {
                "description": "Fetch User Identification information using AccessKey",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Fetch User Identification information using AccessKey",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with user identification",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.UserIdentificationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        },
        "/api/user/quota": {
            "get": {
                "description": "Fetches Quota Information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Fetch User Quota from AccessKey",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User given AccessKey",
                        "name": "access_key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response with user quota",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.UserQuotaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "422": {
                        "description": "Action didn't complete",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.BucketCreateResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "boolean"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.BucketDeleteResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                },
                "has_objects": {
                    "type": "boolean"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.BucketListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_buckets": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.BucketQuotaResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.SingleBucketQuotaResponse"
                    }
                },
                "total_buckets": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectDeleteResponse": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "boolean"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectDownloadResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectHeadResponse": {
            "type": "object",
            "properties": {
                "exists": {
                    "type": "boolean"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectListBody": {
            "type": "object",
            "properties": {
                "last_modified_timestamp": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size_unit": {
                    "type": "string"
                },
                "size_value": {
                    "type": "number"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectListBody"
                    }
                },
                "total_matched_items": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectShareResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.ObjectUploadResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "boolean"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.OperationErrWithMsg": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.SingleBucketQuotaResponse": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                },
                "bucket": {
                    "type": "string"
                },
                "hard_bytes": {
                    "type": "number"
                },
                "hard_bytes_raw": {
                    "type": "integer"
                },
                "hard_bytes_unit": {
                    "type": "string"
                },
                "hard_objects": {
                    "type": "integer"
                },
                "modify_time_stamp": {
                    "type": "string"
                },
                "quota_enabled": {
                    "type": "boolean"
                },
                "tenant": {
                    "type": "string"
                },
                "used_bytes": {
                    "type": "number"
                },
                "used_bytes_raw": {
                    "type": "integer"
                },
                "used_bytes_unit": {
                    "type": "string"
                },
                "used_objects": {
                    "type": "integer"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.UserIdentificationResponse": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "suspended": {
                    "type": "integer"
                },
                "team": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                },
                "user_not_found": {
                    "type": "boolean"
                }
            }
        },
        "gitlab_snapp_ir_platform_s3-panel_internal_storage.UserQuotaResponse": {
            "type": "object",
            "properties": {
                "hard_buckets": {
                    "type": "integer"
                },
                "hard_bytes": {
                    "type": "number"
                },
                "hard_bytes_raw": {
                    "type": "integer"
                },
                "hard_bytes_unit": {
                    "type": "string"
                },
                "hard_objects": {
                    "type": "integer"
                },
                "quota_enabled": {
                    "type": "boolean"
                },
                "used_buckets": {
                    "type": "integer"
                },
                "used_bytes": {
                    "type": "number"
                },
                "used_bytes_raw": {
                    "type": "integer"
                },
                "used_bytes_unit": {
                    "type": "string"
                },
                "used_objects": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "S3 Panel Backend",
	Description:      "Serves the S3 object storage panel backend APIs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
